title: Business Frontpage
description: A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header.

baseurl: /business-frontpage
color-scheme: "cornflowerblue" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
